### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by Ubax** [feelSpace/FSLib-Android#6]
In docs in section about bluetooth connection - https://github.com/feelSpace/FSLib-Android/blob/master/docs/README.md#bluetooth-activation-and-permission-granting - two classes are mentioned that do not exist in the library - `BluetoothActivationFragment ` and `OnBluetoothActivationCallback`.

**Comment by dmeignan** [comment]
Hi,

Thanks for your feedback. I changed the doc to reflect the last version of the FSLib code. The `BluetoothActivationFragment` does not exist anymore (Google seem to have given up on Fragment concept, and it was a mess anyway). There is a replacement in the test application called [`BluetoothCheckActivity`](https://github.com/feelSpace/FSLib-Android/tree/master/app/src/main/java/de/feelspace/fslibtest). However, it is not optimal because it requires that the Activity from which you connect extends this `BluetoothCheckActivity`, and consequently extends `AppCompatActivity`.

I now mentioned in the docs that it is better to adapt or implement your own solution for permissions and services check. The `BluetoothCheckActivity` is only a quick way to make some tests. Also, the [`RequestPermission`-Contract](https://developer.android.com/training/permissions/requesting#request-permission) from AndroidX library may be used for more flexibility on where your application requests permissions. I didn't implement this in the FSLib because the code and recommended workflow is awful.

**Comment by dmeignan** [comment]
Docs updated in commit 4011d82694322657018a78abd4ef7a605338ac92
